// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "GET",
    id: "c61dfe88-9781-45e5-bd12-f1b6d7903652",
    method: "GET",
    address: "http:///"
  });

  postman[Request]({
    name: "POST",
    id: "e4835f6d-442b-439e-8fd6-8c73bfa25b3b",
    method: "GET",
    address: "http:///"
  });
}
