// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "GET Sever",
    id: "0d451d98-d16b-40d9-b88f-17717a19535e",
    method: "GET",
    address: "http://localhost:3000"
  });

  postman[Request]({
    name: "GET Sever Complex",
    id: "73979cd5-869e-4583-b730-c5d6c13577fd",
    method: "GET",
    address: "http://localhost:3000/todo"
  });

  postman[Request]({
    name: "GET Sever Complex 2",
    id: "710d741c-d2b4-4990-aeb7-517c0c22906a",
    method: "GET",
    address: "http://localhost:3000/todo/Diego"
  });

  postman[Request]({
    name: "Post Server",
    id: "3c47eef5-b003-4d5a-87d7-f8f3be016438",
    method: "GET",
    address: "http://localhost:3000/todo"
  });
}
